# Generated by Django 5.1.6 on 2025-03-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activity_level",
            field=models.CharField(
                choices=[
                    (1, "Sedentary (office job)"),
                    (2, "Light Exercise (1-2 days/week)"),
                    (3, "Moderate Exercise (3-5 days/week)"),
                    (4, "Heavy Exercise (6-7 days/week)"),
                    (5, "Athlete (2x per day)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other/Undisclosed")],
                max_length=20,
            ),
        ),
    ]
