# Generated by Django 5.1.6 on 2025-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_activity_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("Sedentary", "Sedentary (office job)"),
                    ("Light", "Light Exercise (1-2 days/week)"),
                    ("Moderate", "Moderate Exercise (3-5 days/week)"),
                    ("Heavy", "Heavy Exercise (6-7 days/week)"),
                    ("Athlete", "Athlete (2x per day)"),
                ],
                max_length=50,
            ),
        ),
    ]
