# Generated by Django 5.1.6 on 2025-03-03 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
