# Generated by Django 5.1.6 on 2025-03-24 19:44

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=320,
                unique=True,
                validators=[users.models.no_whitespace_validator],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                max_length=45, validators=[users.models.no_whitespace_validator]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                max_length=45, validators=[users.models.no_whitespace_validator]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[users.models.no_whitespace_validator],
            ),
        ),
    ]
