# Generated by Django 5.1.6 on 2025-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_customuser_email_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="dailyCalorieCount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="log",
            name="dailyOptimalCount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
