# Generated by Django 5.1.6 on 2025-04-20 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_log_options_log_log_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapilimit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userapilimit', to=settings.AUTH_USER_MODEL),
        ),
    ]
