# Generated by Django 5.1.6 on 2025-04-20 22:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userapilimit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapilimit',
            name='last_call',
        ),
        migrations.AddField(
            model_name='userapilimit',
            name='last_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userapilimit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_limit', to=settings.AUTH_USER_MODEL),
        ),
    ]
