# Generated by Django 5.1.6 on 2025-04-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_userapilimit_last_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapilimit',
            name='calls_remaining',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
