# Generated by Django 5.1.6 on 2025-02-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other/Undisclosed', 'Other/Undisclosed')], max_length=20)),
                ('age', models.IntegerField()),
                ('email_address', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=64)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary (office job)'), ('Light Exercise', 'Light Exercise (1-2 days/week)'), ('Moderate Exercise', 'Moderate Exercise (3-5 days/week)'), ('Heavy Exercise', 'Heavy Exercise (6-7 days/week)'), ('Athlete', 'Athlete (2x per day)')], max_length=20)),
            ],
        ),
    ]
