# Generated by Django 5.1.6 on 2025-03-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumedfood',
            name='date_consumed',
            field=models.DateField(),
        ),
    ]
