# Generated by Django 5.1.6 on 2025-04-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_foodhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumedfood',
            name='calories_per_serving',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
