# Generated by Django 5.1.6 on 2025-04-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_consumedfood_calories_per_serving"),
        ("users", "0016_alter_userapilimit_calls_remaining"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consumedfood",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="consumedfood",
            name="log",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumed_foods",
                to="users.log",
                verbose_name="Log Entry",
            ),
        ),
        migrations.RemoveField(
            model_name="consumedfood",
            name="user",
        ),
    ]
